version: "3"
services:
  chrome:
    image: selenium/node-chrome:4.15.0-20231108
    shm_size: 2gb
    depends_on:
      - selenium-hub
    deploy:
      replicas: 1
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=1
      - SE_VNC_NO_PASSWORD=1

  edge:
    image: selenium/node-edge:4.15.0-20231108
    shm_size: 2gb
    depends_on:
      - selenium-hub
    deploy:
      replicas: 1
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  firefox:
    image: selenium/node-firefox:4.15.0-20231108
    shm_size: 2gb
    depends_on:
      - selenium-hub
    deploy:
      replicas: 1
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=1
      - SE_VNC_NO_PASSWORD=1

  selenium-hub:
    image: selenium/hub:4.15.0-20231108    
    container_name: selenium-hub
  vendor-portal:
   image: vinsdocker/selenium
   depends_on:
    - chrome
   environment:
    - BROWSER=chrome
    - HUB_HOST=selenium-hub
    - THREAD_COUNT=3
    - TEST_SUITE=vendor-portal.xml
   volumes:
   - ./output/vendor-portal:/home/selenium-docker/test-output
  flight-reservation:
   image: vinsdocker/selenium
   depends_on:
    - firefox
   environment:
    - BROWSER=firefox
    - HUB_HOST=selenium-hub
    - THREAD_COUNT=3
    - TEST_SUITE=flight-reservation.xml
   volumes:
   - ./output/flight-reservation:/home/selenium-docker/test-output

