version: "3"
services:
  chrome:
    image: selenium/node-chrome:4.15.0-20231108
    shm_size: 2gb
    depends_on:
      - selenium-hub
    deploy:
      replicas: 1
    env_file: .env

  edge:
    image: selenium/node-edge:4.15.0-20231108
    shm_size: 2gb
    depends_on:
      - selenium-hub
    deploy:
      replicas: 1
    env_file: .env

  firefox:
    image: selenium/node-firefox:4.15.0-20231108
    shm_size: 2gb
    depends_on:
      - selenium-hub
    deploy:
      replicas: 1
    env_file: .env

  selenium-hub:
    image: selenium/hub:4.15.0-20231108    
    container_name: selenium-hub